### ISSUE TITLE
Play history?

### ISSUE THREAD

**Issue by aniqueta** [cetteup/transfer-plex-user-viewstate#1]
Hi @cetteup - My mistake for posting this in the incorrect repository. Thanks for creating this tool. It's not clear from the code (since I don't know the Plex DB structure well enough) if this also migrates play history. Is "last-played-at" just one date or an array of dates? Thanks.

**Comment by cetteup** [comment]
Hey @aniqueta.

Good question, I actually had to check. But the answer is: No, it does not transfer play history. The relevant table only contains a single `last_played_at` date and a `view_count` column.

The detailed play history seems to be stored elsewhere. And I don't know where off the top of my head.

Just to provide some background: I wrote the script because I switched from a managed account to one the library was shared with and wanted to keep my progress for TV shows etc. I did not look into transferring the play history at all, as that was not required to achieve what I wanted to achieve.

Hope this answers your question!

**Comment by cetteup** [comment]
For future reference: Just found where the play history is stored. The table is called `metadata_item_views` and here is what it looks like:

```sql
CREATE TABLE "metadata_item_views" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "account_id" integer, "guid" varchar(255), "metadata_type" integer, "library_section_id" integer, "grandparent_title" varchar(255), "parent_index" integer, "parent_title" varchar(255), "index" integer, "title" varchar(255), "thumb_url" varchar(255), "viewed_at" datetime, 'grandparent_guid' varchar(255), 'originally_available_at' datetime, 'device_id' integer);
```

**Comment by aniqueta** [comment]
Thanks @cetteup. I have the same use case. Migrating a managed account to a full account with shared library access. Play history would make the data migration complete, but it's not critical and more for posterity. Seems like this would be a matter of taking the logic in this script, copying it, and then adapting it for this additional table? Thanks.

**Comment by cetteup** [comment]
I looked into it, will add support for transferring the  play history items tomorrow.

**Comment by aniqueta** [comment]
@cetteup Thank you!

Tautulli is not a problem at all for me.

**Comment by aniqueta** [comment]
@cetteup Thank you! This works quite well.
