### ISSUE TITLE
Any way to copy view states across different Plex servers?

### ISSUE THREAD

**Issue by SteveW25561** [cetteup/transfer-plex-user-viewstate#4]
Any chance you might add the ability to copy viewstates across accounts on different Plex servers? 

My use case: I have Plex running on my Synology and my Mac, both pointing to the same directories on the Synology, so the library content is identical. 

Having 2 servers with the same content allows redundancy but also speed (Macbook is much faster for encodes, etc than the Synology Plex server, but the Synology instance is up and running 24/7 even if my Mac is offline or out of the house).

The old plex-sync (https://github.com/jacobwgillespie/plex-sync) can sync watch status across servers, but seems to miss a few items, and doesn't transfer the current viewed time/placeholder like yours does.

**Comment by cetteup** [comment]
I don't think this is something that this project can provide. It relies on direct database access, meaning the server should be should be shut down in order to prevent simultaneous access to the db by Plex itself and the script. In order to achieve this for two servers, you'd have to coordinate both servers to stop Plex before you need to somehow facilitate file access to both the local and remote database.

So, it's not something I see as feasible with this approach. Would probably be easier to revive plex-sync (if the APIs it uses are still present).
